#!/usr/bin/env ruby
# This is a mess but it'll do for now

require 'shellwords'

all_data = IO.readlines('results/timings.txt').map(&:strip)
all_data.reject! {|line| line.start_with?('#') }

by_label = {}
all_data.each do |line|
  row = line.split(/\s+/)
  label = row[0]
  by_label[label] ||= []
  by_label[label] << row
end

labels = by_label.keys
labels.sort!

labels.each do |label|
  by_label[label].sort_by! {|row| row[1].to_f }
end

plots = []

dataset_path = 'results/gnuplot_dataset.txt'
File.open(dataset_path, 'wb') do |datafile|
  dataset_index = 0
  
  labels.each do |label|
    unless by_label[label].empty?
      datafile << "# " << label << "\n"
      by_label[label].each do |row|
        datafile << row[1..2].join(" ") << "\n"
      end
      datafile << "\n\n"
      
      plots << "'#{dataset_path}' index #{dataset_index} using 1:2 title '#{label}' with lines"
      dataset_index += 1
    end
  end
  
  labels.each do |label|
    if by_label[label].any? {|row| row[3] == '1' }
      datafile << "# " << label << " errors\n"
      by_label[label].each do |row|
        datafile << row[1..2].join(" ") << "\n" if row[3] == '1'
      end
      datafile << "\n\n"
      
      plots << "'#{dataset_path}' index #{dataset_index} using 1:2 title '#{label} errors' with points"
      dataset_index += 1
    end
  end
end

gnuplot_script = "plot " + plots.join(',')
gnuplot_cmd = Shellwords.join(['gnuplot', '--persist', '-e', gnuplot_script])
system(gnuplot_cmd)


puts "Success rates:"
labels.each do |label|
  rows = by_label[label]
  successful = rows.select {|row| row[3] == '0'}.size
  total = rows.size
  success_rate = successful / total.to_f
  printf("  %s: %d / %d  (%.1f%%)\n", label, successful, total, success_rate*100)
end

